FROM n8nio/n8n:latest

ENV PORT=5678
ENV N8N_PORT=5678
ENV NODE_OPTIONS="--max-old-space-size=320"
ENV EXECUTIONS_DATA_PRUNE=true
ENV EXECUTIONS_DATA_MAX_AGE=24
ENV N8N_TEMPLATES_ENABLED=false
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
ENV DB_SQLITE_VACUUM_ON_STARTUP=false
ENV DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false

EXPOSE 5678
