FROM n8nio/n8n:latest

ENV PORT=5678
ENV N8N_PORT=5678
ENV NODE_OPTIONS="--max-old-space-size=460"
ENV EXECUTIONS_DATA_PRUNE=true
ENV EXECUTIONS_DATA_MAX_AGE=168
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

EXPOSE 5678
